ALTER TABLE contract_leave_limits
  ADD COLUMN imported TINYINT(1) NOT NULL DEFAULT 0 AFTER period_end;

CREATE TABLE IF NOT EXISTS leave_years (
  year SMALLINT UNSIGNED NOT NULL,
  is_open TINYINT(1) NOT NULL DEFAULT 0,
  imported_by_id INT UNSIGNED NULL,
  imported_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (year),
  CONSTRAINT fk_leave_years_imported_by_id
    FOREIGN KEY (imported_by_id) REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;
